title: Benjamin Wulf
description: Portfolio
url: "https://benjaminwulf.com/"
exclude:
# Inside _config.yml
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - node_modules
  - vendor